# Generated by Django 5.0.7 on 2025-04-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_product_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="autor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
