# Generated by Django 5.0.7 on 2025-05-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_remove_product_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="autor",
            field=models.CharField(
                blank=True, default="Unknown", max_length=100, null=True
            ),
        ),
    ]
