# Generated by Django 5.0.6 on 2024-06-13 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='products/images/')),
                ('pdf', models.FileField(upload_to='products/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.FloatField(default=0.0)),
                ('stock', models.IntegerField(default=0)),
                ('cart', models.ManyToManyField(related_name='carted_products', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(related_name='wishlisted_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
