# Generated by Django 5.0.7 on 2025-01-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
