# Generated by Django 5.0.7 on 2025-01-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_downvotes_review_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
